### ISSUE TITLE
Add sections in the navigation

### ISSUE THREAD

**Issue by seb86** [co-cart/co-cart-docs#25]
The new sections will provide dividers for CoCart, Pro, Products and other add-ons coming so it's all together and enable the search to find through all API's.

This will also adjust the navigation for current content but will increase the chances for the user to find what they are looking for quicker.

**Comment by seb86** [comment]
Example of giving some space to separate sections.
```css
a[data-title="Demo CoCart"] {
    margin-top: 30px;
}
```
